nb_threads = 2
update_templates = true

# If a cosmogony_file is configured, ntfs2mimir will read the admins from this file.
# If such a file is not configured, ntfs2mimir will read the admins from elasticsearch

# cosmogony_file = "/home/pascal/mimirsbrunn/cosmogony-europe.jsonl.gz"

# configuration for reading the cosmogony file
french_id_retrocompatibility = true
langs = [ "fr" ]

[container]
  name = "addr"
  dataset = "fr"
  visibility = "public"
  number_of_shards = 1
  number_of_replicas = 0
