stages:
  - build
  - development
  - integration
  - production

.build:
  stage: build
  before_script:
    - source ci/bootstrap.sh
    - docker login
        --username "$CI_REGISTRY_USER"
        --password-stdin "$CI_REGISTRY" <<< "$CI_REGISTRY_PASSWORD"
  variables:
    COMPOSE_DOCKER_CLI_BUILD: "1"
    COMPOSE_FILE: "ci/docker-compose.build.yml"
    DOCKER_BUILDKIT: "1"
    DOCKER_CONFIG: "$CI_PROJECT_DIR/.docker"
    GIT_SUBMODULE_STRATEGY: recursive
    IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"
  artifacts:
    paths:
      - "ci/"
  tags:
    - light

build bragi:
  extends: .build
  variables:
    DOCKER_CONFIG: "$CI_PROJECT_DIR/bragi/.docker"
  script:
    - docker-compose build bragi
    - docker-compose push bragi

build mimirsbrunn:
  extends: .build
  variables:
    DOCKER_CONFIG: "$CI_PROJECT_DIR/mimirsbrunn/.docker"
  script:
    - docker-compose build mimirsbrunn
    - docker-compose push mimirsbrunn

.deploy:
  image: registry.qwant.ninja/docker/kubectl:1.19.1
  variables:
    ARGOAPP_REPO_BASEDIR: "deployments"
    ARGOAPP_REPO_URL_SSH: "git@git.qwant.ninja:teams/search-apps/argo_apps.git"
    ARGOCD_APP_ENVIRONMENT: "$CI_ENVIRONMENT_NAME"
  before_script:
    - source ci/bootstrap.sh
  when: manual
  tags:
    - docker

.deploy:mimir:
  extends: .deploy
  variables:
    ARGOAPP_REPO_PATH: "maps/mimirsbrunn"
    ARGOAPP_REPO_BRANCH: "QMAPS-2829"
    IMAGE_VERSION_FILE: "overlays/${CI_JOB_STAGE}/kustomization.yaml"
  resource_group: "mimir-$CI_JOB_STAGE"
  script:
    - sync-version-argocd 
      --docker-image "$CI_COMMIT_SHORT_SHA"
      --image-version-object-path "(.images[] | select(.name == \"$CI_REGISTRY_IMAGE/mimir\") | .newTag)"

.deploy:bragi:
  extends: .deploy
  variables:
    ARGOAPP_REPO_PATH: "maps/bragi"
    ARGOAPP_REPO_BRANCH: "master"
    IMAGE_VERSION_FILE: "versions/${CI_JOB_STAGE}.yaml"
  resource_group: "bragi-$CI_JOB_STAGE"
  before_script:
    - source ci/bootstrap.sh
  script:
    - sync-version-argocd 
      --docker-image "$CI_REGISTRY_IMAGE/bragi:$CI_COMMIT_SHORT_SHA"
      --image-version-object-path ".image"

#
# Deploy Mimir docker image
#
deploy mimir development:
  stage: development
  extends:
    - .deploy:mimir

deploy mimir integration:
  stage: integration
  extends:
    - .deploy:mimir

deploy mimir production:
  stage: production
  extends:
    - .deploy:mimir

#
# Deploy Bragi docker image
#
deploy bragi development:
  stage: development
  extends:
    - .deploy:bragi

deploy bragi integration:
  stage: integration
  extends:
    - .deploy:bragi

deploy bragi production:
  stage: production
  extends:
    - .deploy:bragi
