[logging]
  path = "./logs"

[container]
  dataset = "fr"

# This section is ignored if mimirsbrunn is compiled without the `db-storage`
# option.
[database]
  file = "/tmp/osm_db.tmp"
  buffer_size = 50_000

[pois]
  import = false
  [pois.config]
    [[pois.config.types]]
      id = "poi_type:amenity:college"
      name = "École"
    [[pois.config.types]]
      id = "poi_type:amenity:university"
      name = "Université"
    [[pois.config.types]]
      id = "poi_type:amenity:theatre"
      name = "Théâtre"
    [[pois.config.types]]
      id = "poi_type:amenity:hospital"
      name = "Hôpital"
    [[pois.config.types]]
      id = "poi_type:amenity:post_office"
      name = "Bureau de poste"
    [[pois.config.types]]
      id = "poi_type:amenity:bicycle_rental"
      name = "Station VLS"
    [[pois.config.types]]
      id = "poi_type:amenity:bicycle_parking"
      name = "Parking vélo"
    [[pois.config.types]]
      id = "poi_type:amenity:parking"
      name = "Parking"
    [[pois.config.types]]
      id = "poi_type:amenity:police"
      name = "Police, gendarmerie"
    [[pois.config.types]]
      id = "poi_type:amenity:townhall"
      name = "Mairie"
    [[pois.config.types]]
      id = "poi_type:leisure:garden"
      name = "Jardin"
    [[pois.config.types]]
      id = "poi_type:leisure:park"
      name = "Parc, espace vert"

    [[pois.config.rules]]
      type = "poi_type:amenity:college"
      [[pois.config.rules.osm_tags_filters]]
        key = "amenity"
        value = "college"
    [[pois.config.rules]]
      type = "poi_type:amenity:university"
      [[pois.config.rules.osm_tags_filters]]
        key = "amenity"
        value = "university"
    [[pois.config.rules]]
      type = "poi_type:amenity:theatre"
      [[pois.config.rules.osm_tags_filters]]
        key = "amenity"
        value = "theatre"
    [[pois.config.rules]]
      type = "poi_type:amenity:hospital"
      [[pois.config.rules.osm_tags_filters]]
        key = "amenity"
        value = "hospital"
    [[pois.config.rules]]
      type = "poi_type:amenity:post_office"
      [[pois.config.rules.osm_tags_filters]]
        key = "amenity"
        value = "post_office"
    [[pois.config.rules]]
      type = "poi_type:amenity:bicycle_rental"
      [[pois.config.rules.osm_tags_filters]]
        key = "amenity"
        value = "bicycle_rental"
    [[pois.config.rules]]
      type = "poi_type:amenity:bicycle_parking"
      [[pois.config.rules.osm_tags_filters]]
        key = "amenity"
        value = "bicycle_parking"
    [[pois.config.rules]]
      type = "poi_type:amenity:parking"
      [[pois.config.rules.osm_tags_filters]]
        key = "amenity"
        value = "parking"
    [[pois.config.rules]]
      type = "poi_type:amenity:police"
      [[pois.config.rules.osm_tags_filters]]
        key = "amenity"
        value = "police"
    [[pois.config.rules]]
      type = "poi_type:amenity:townhall"
      [[pois.config.rules.osm_tags_filters]]
        key = "amenity"
        value = "townhall"
    [[pois.config.rules]]
      type = "poi_type:leisure:garden"
      [[pois.config.rules.osm_tags_filters]]
        key = "leisure"
        value = "garden"
    [[pois.config.rules]]
      type = "poi_type:leisure:park"
      [[pois.config.rules.osm_tags_filters]]
        key = "leisure"
        value = "park"

[streets]
  import = false
  [streets.exclusions]
    # See [OSM Key Highway](https://wiki.openstreetmap.org/wiki/Key:highway) for background.
    highway = [ "bus_guideway", "bus_stop", "elevator", "escape", "platform" ]
    public_transport = [ "platform", "hub" ]
