[elasticsearch]
url = "http://localhost:9200"
timeout = 100
version_req = ">=7.13.0"

# Number of documents loaded per request when performing a `list_documents`
scroll_chunk_size = 1000

# Liveness of the PIT while performing a `list_documents`.
scroll_pit_alive = "1m"
