[docker]
	# Timeout for calls to docker engine (ms)
	timeout = 5000

	# Time to wait after container creation (ms)
	container_wait = 5000

	# Time to wait for Elasticsearch to be available.
	elasticsearch_wait = 30000

  # Time to wait after container has been stopped and removed
	cleanup_wait = 5

	[docker.container]
	  # Docker image
		image = "docker.elastic.co/elasticsearch/elasticsearch:7.13.0"

		# Name of the container
		name = "mimir-test"

		# Memory usage allocated by the docker engine
		memory = 1024 # In Mb

		# List of environment variables passed to the docker engine for
		# the creation of the image.
		vars = ["discovery.type=single-node"]

	[docker.version]
    major = 1
    minor = 24

