[docker]
	timeout = 5000
	container_wait = 5 # Time to wait after container creation (sec)
	elasticsearch_wait = 30 # Time to wait for Elasticsearch to be available.
	cleanup_wait = 5

	[docker.container]
		image = "docker.elastic.co/elasticsearch/elasticsearch:7.13.0"
		name = "mimir-test"
		memory = 1024 # In Mb
		vars = ["discovery.type=single-node"]

	[docker.version]
	  major = 1
		minor = 24

