nb_threads = 1
update_templates = true


# If a cosmogony_file is configured, ntfs2mimir will read the admins from this file.
# If such a file is not configured, ntfs2mimir will read the admins from elasticsearch

# cosmogony_file = "/home/pascal/mimirsbrunn/cosmogony-europe.jsonl.gz"

# configuration for reading the cosmogony file
french_id_retrocompatibility = true
langs = [ "fr" ]

[container]
  name = "stop"
  dataset = "third_local"
  visibility = "public"
  number_of_shards = 1
  number_of_replicas = 0

# RapidTransit, Train, Air, Boat, Ferry, LocalTrain, LongDistanceTrain = 8
[[physical_mode_weight]]
  id = "RapidTransit"
  weight = 8.0
[[physical_mode_weight]]
  id = "Train"
  weight = 8.0
[[physical_mode_weight]]
  id = "Air"
  weight = 8.0
[[physical_mode_weight]]
  id = "Boat"
  weight = 8.0
[[physical_mode_weight]]
  id = "Ferry"
  weight = 8.0
[[physical_mode_weight]]
  id = "LocalTrain"
  weight = 8.0
[[physical_mode_weight]]
  id = "LongDistanceTrain"
  weight = 8.0

# Metro, BusRapidTransit = 5
[[physical_mode_weight]]
  id = "Metro"
  weight = 5.0
[[physical_mode_weight]]
  id = "BusRapidTransit"
  weight = 5.0

# Coach = 3
[[physical_mode_weight]]
  id = "Coach"
  weight = 3.0

# Tramway, RailShuttle, Funicular, Shuttle, SuspendedCableCar = 2
[[physical_mode_weight]]
  id = "Tramway"
  weight = 2.0
[[physical_mode_weight]]
  id = "RailShuttle"
  weight = 2.0
[[physical_mode_weight]]
  id = "Funicular"
  weight = 2.0
[[physical_mode_weight]]
  id = "Shuttle"
  weight = 2.0
[[physical_mode_weight]]
  id = "SuspendedCableCar"
  weight = 2.0

# Bus = 1
[[physical_mode_weight]]
  id = "Bus"
  weight = 1.0
