[package]
name = "ctl-importer"
version = "0.1.0"
edition = "2021"

[dependencies]
exporter-config.workspace = true
elastic-client.workspace = true
tokio.workspace = true
clap.workspace = true
anyhow.workspace = true
tracing.workspace = true
serde.workspace = true
