[package]
name = "geo-query"
version = "0.1.0"
edition = "2021"

[dependencies]
elastic-query-builder.workspace = true
elastic-client.workspace = true
places.workspace = true
serde-helpers.workspace = true

clap.workspace = true
serde_json.workspace = true
tokio.workspace = true
