name: Benchmark Tests
permissions:
  contents: write
  deployments: write

on:
  push:

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        name: Setup rust toolchain
        with:
          toolchain: 1.54.0
          profile: minimal
          components: rustfmt, clippy

      - name: Run benchmark
        run: cargo cargo +nightly bench | tee benches/results/output.txt

      - name: Store benchmark
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Mimirsbrunn Benchmark
          tool: 'cargo'
          output-file-path: benches/results/output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@crocme10'
