name: Create and publish docker images

on:
  pull_request:
  push:
    branches:
      - master
      - release
    tags:
      - 'v*'

env:
  DOCKER_BUILDKIT: 1
  DOCKER_ORG: navitia

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - bragi
          - mimirsbrunn

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - Read rustup toolchain version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./rust-toolchain

      - name: Login to DockerHub
        if: github.event_name == 'push'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get image name
        run: |
          VERSION=${GITHUB_REF#refs/*/}
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            IMAGE_TAG=$GITHUB_SHA
          elif [ "$VERSION" == "master" ]; then
            IMAGE_TAG=latest
          else
            IMAGE_TAG=$VERSION
          fi
          echo "DOCKER_IMAGE=$DOCKER_ORG/${{ matrix['image'] }}:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build docker image
        run: >-
          docker build
          --build-arg RUST_VERSION="${{ steps.version.outputs.content }}"
          --file docker/${{ matrix['image'] }}/Dockerfile
          --label "org.label-schema.vcs-ref=$GITHUB_SHA"
          --tag $DOCKER_IMAGE
          .

      - if: github.event_name == 'push'
        run: docker push $DOCKER_IMAGE
