name: Matser_Packages

on:
  push:
    branches:
      - master

jobs:
  package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: jessie
            packages: pkg-config libssl-dev
            rust: 1.56.1

          - version: buster
            packages: pkg-config libssl-dev
            rust: 1.56.1

    container: debian:${{matrix.version}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install requirements
        run: |
          apt-get update
          apt-get install -y curl wget build-essential
          apt-get install -y ${{ matrix.packages }}
      # TODO :
      # Remove this step after ES migration 2->7.
      # We need it to make version 2 and 7 coexist.
      # Be careful, binaries will not have the same name !
      - name: Temporary rename binaries with 7
        run: |
          mv src/bin/bano2mimir.rs src/bin/bano2mimir7.rs
          mv src/bin/cosmogony2mimir.rs src/bin/cosmogony2mimir7.rs
          mv src/bin/ctlmimir.rs src/bin/ctlmimir7.rs
          mv src/bin/openaddresses2mimir.rs src/bin/openaddresses2mimir7.rs
          mv src/bin/osm2mimir.rs src/bin/osm2mimir7.rs
          mv src/bin/poi2mimir.rs src/bin/poi2mimir7.rs
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
      - name: Build package
        run: ./scripts/build_deb.sh ${{ matrix.version }} 7
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: debian-package-master
          path: ./scripts/deb-scratch/*

      - name: slack notification (the job has failed)
        if: failure()
        run: |
          apt-get update
          apt install -y httpie
          echo '{"text":":Warning: Github Actions: build packages for branch master failed ! (https://github.com/CanalTP/mimirsbrunn/actions/workflows/master.yml)."}' | http --json POST ${{secrets.SLACK_NAVITIA_AUTOCOMPLETE_TEAM_URL}}
