name: CI

on:
  push:
  pull_request:

jobs:
  rustfmt:
    name: Code Validation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: 1.54.0
    - name: Check formatting
      run: make format
    - name: Linting
      run: make lint
    - name: Running unit tests and E2E tests
      run: make test
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: 'cargo'
        output-file-path: output.txt
