name: Build and Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.54.0

      - uses: Swatinem/rust-cache@v1

      - name: Formatting checks
        run: make format

      - name: Linting checks
        run: make lint

      - name: Unit Tests and E2E Tests checks
        run: make test
